version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - /home/florian/repo/crb/docker-data/mariadb:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=Frank83M1$$1on_H0rse
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=8acb9c7bde
  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'wordpress_data:/home/florian/repo/crb/docker-data'
      - /home/florian/repo/crb/docker-data/wordpress:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=8acb9c7bde
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
